# Generated by Django 6.0 on 2025-12-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'Нужно сделать'), ('in_progress', 'В работе'), ('review', 'Ревью'), ('blocked', 'Ждёт связанные таски'), ('ready_test', 'Готово к тестированию'), ('testing', 'Тестирование'), ('tested', 'Протестировано'), ('ready_deploy', 'Готово к деплою'), ('done', 'Выполнено')], default='todo', max_length=20, verbose_name='Статус'),
        ),
    ]
