# Generated by Django 6.0 on 2025-12-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_is_completed_task_priority_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Оценка времени (часы)'),
        ),
    ]
