# Generated by Django 6.0 on 2025-12-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_estimated_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='blocked_by',
            field=models.ManyToManyField(blank=True, related_name='blocking', to='tasks.task', verbose_name='Блокируется задачами'),
        ),
    ]
